import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "NOMBRE", uid: "name", sortable: true},
  {name: "ROLE", uid: "role", sortable: true},
  {name: "TELÉFONO", uid: "telefono", sortable: true},
  {name: "USUARIO", uid: "usuario", sortable: true},
  {name: "EMAIL", uid: "email"},
  {name: "ESTATUS", uid: "status", sortable: true},
  {name: "ACCIONES", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Vacation", uid: "vacation"},
];

const users = [
    {
      id: 1,
      name: "Adolfo",
      apellidoPaterno: "Ramos",
      apellidoMaterno: "Cruz",
      role: "CEO",
      telefono: "2315937778",
      usuario: "adolfoHiT",
      status: "active",
      avatar: "/images/user.png",
      email: "tony.reichert@example.com",
    },
    {
      id: 2,
      name: "Ana",
      apellidoPaterno: "Pérez",
      apellidoMaterno: "López",
      role: "Manager",
      telefono: "5551234567",
      usuario: "anaPeLo",
      status: "active",
      avatar: "/images/user.png",
      email: "ana.perez@example.com",
    },
    {
      id: 3,
      name: "Juan",
      apellidoPaterno: "Gómez",
      apellidoMaterno: "García",
      role: "Developer",
      telefono: "9876543210",
      usuario: "juanGoGa",
      status: "active",
      avatar: "/images/user.png",
      email: "juan.gomez@example.com",
    },
    {
      id: 4,
      name: "María",
      apellidoPaterno: "Hernández",
      apellidoMaterno: "Rodríguez",
      role: "Designer",
      telefono: "1234567890",
      usuario: "mariaHeRo",
      status: "active",
      avatar: "/images/user.png",
      email: "maria.hernandez@example.com",
    },
    {
      id: 5,
      name: "Pedro",
      apellidoPaterno: "Martínez",
      apellidoMaterno: "Sánchez",
      role: "Sales Manager",
      telefono: "3210987654",
      usuario: "pedroMaSa",
      status: "active",
      avatar: "/images/user.png",
      email: "pedro.martinez@example.com",
    },
    {
      id: 6,
      name: "Lucía",
      apellidoPaterno: "López",
      apellidoMaterno: "Álvarez",
      role: "Accountant",
      telefono: "6543210987",
      usuario: "luciaLoAl",
      status: "active",
      avatar: "/images/user.png",
      email: "pedro.martinez@example.com",
    },
    {
      id: 7,
      name: "Gabriel",
      apellidoPaterno: "González",
      apellidoMaterno: "Ochoa",
      role: "Engineer",
      telefono: "7890123456",
      usuario: "gabrielGoOc",
      status: "active",
      avatar: "/images/user.png",
      email: "gabriel.gonzalez@example.com",
    },
    {
      id: 8,
      name: "Sofía",
      apellidoPaterno: "Pérez",
      apellidoMaterno: "Guzmán",
      role: "Customer Service Representative",
      telefono: "9876543210",
      usuario: "sofiaPeGu",
      status: "active",
      avatar: "/images/user.png",
      email: "sofia.perez@example.com",
    },
    {
      id: 9,
      name: "Daniel",
      apellidoPaterno: "García",
      apellidoMaterno: "Rivera",
      role: "Marketing Manager",
      telefono: "1234567890",
      usuario: "danielGaRi",
      status: "active",
      avatar: "/images/user.png",
      email: "daniel.garcia@example.com",
    },
    {
      id: 10,
      name: "Andrea",
      apellidoPaterno: "López",
      apellidoMaterno: "Hernández",
      role: "Data Scientist",
      telefono: "3210987654",
      usuario: "andreaLoHe",
      status: "active",
      avatar: "/images/user.png",
      email: "andrea.lopez@example.com",
    },
    {
      id: 11,
      name: "Luis",
      apellidoPaterno: "Álvarez",
      apellidoMaterno: "García",
      role: "Teacher",
      telefono: "6543210987",
      usuario: "luisAlGa",
      status: "active",
      avatar: "/images/user.png",
      email: "luis.alvarez@example.com",
    },
    {
      id: 12,
      name: "Anahí",
      apellidoPaterno: "González",
      apellidoMaterno: "Martínez",
      role: "Doctor",
      telefono: "7890123456",
      usuario: "anahiGoMa",
      status: "active",
      avatar: "/images/user.png",
      email: "anahi.gonzalez@example.com",
    },
    {
      id: 13,
      name: "José",
      apellidoPaterno: "López",
      apellidoMaterno: "Pérez",
      role: "Lawyer",
      telefono: "9876543210",
      usuario: "joseLoPe",
      status: "active",
      avatar: "/images/user.png",
      email: "jose.lopez@example.com",
    },
    {
      id: 14,
      name: "Martín",
      apellidoPaterno: "Muñoz",
      apellidoMaterno: "Rodríguez",
      role: "Artist",
      telefono: "1234567890",
      usuario: "martinMuRo",
      status: "active",
      avatar: "/images/user.png",
      email: "martin.munoz@example.com",
    },
    {
      id: 15,
      name: "Paola",
      apellidoPaterno: "Hernández",
      apellidoMaterno: "Sánchez",
      role: "Writer",
      telefono: "3210987654",
      usuario: "paolaHeSa",
      status: "active",
      avatar: "/images/user.png",
      email: "paola.hernandez@example.com",
    },

    {
      id: 16,
      name: "Claudia",
      apellidoPaterno: "Rivera",
      apellidoMaterno: "García",
      role: "Entrepreneur",
      telefono: "6543210987",
      usuario: "claudiaRiGa",
      status: "active",
      avatar: "/images/user.png",
      email: "claudia.rivera@example.com",
    },
    {
      id: 17,
      name: "Ángel",
      apellidoPaterno: "Martínez",
      apellidoMaterno: "Hernández",
      role: "Student",
      telefono: "7890123456",
      usuario: "angelMaHe",
      status: "active",
      avatar: "/images/user.png",
      email: "angel.martinez@example.com",
    },
    {
      id: 18,
      name: "Gabriela",
      apellidoPaterno: "López",
      apellidoMaterno: "Gómez",
      role: "Retired",
      telefono: "9876543210",
      usuario: "gabrielaLoGo",
      status: "active",
      avatar: "/images/user.png",
      email: "gabriela.lopez@example.com",
    },
    {
      id: 19,
      name: "Juan Carlos",
      apellidoPaterno: "Pérez",
      apellidoMaterno: "Rodríguez",
      role: "Homemaker",
      telefono: "1234567890",
      usuario: "juanCaPeRo",
      status: "active",
      avatar: "/images/user.png",
      email: "juan.carlos.perez@example.com",
    },
    {
      id: 20,
      name: "María José",
      apellidoPaterno: "González",
      apellidoMaterno: "Sánchez",
      role: "Unemployed",
      telefono: "3210987654",
      usuario: "mariaJoGoSa",
      status: "active",
      avatar: "/images/user.png",
      email: "maria.jose.gonzalez@example.com",
    },
  
];

export {columns, users, statusOptions};
